name: Commit

on:
  push:
    branches: [master]

jobs:
  Build:
    runs-on: macos-10.15
    timeout-minutes: 15
    steps:
      - name: "Checkout Project"
        uses: actions/checkout@v2

      - name: "Select Xcode 12.0.1"
        uses: devbotsxyz/xcode-select@work
        with:
          version: "12.0.0"

      - name: "Import Certificate: Development"
        uses: devbotsxyz/import-signing-certificate@v1
        with:
          certificate-data: ${{ secrets.DEVELOPMENT_CERTIFICATE_DATA }}
          certificate-passphrase: ${{ secrets.DEVELOPMENT_CERTIFICATE_PASSPHRASE }}
          keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}

      - name: "Build & Archive"
        uses: devbotsxyz/xcode-archive@v1
