name: Pull Request

on: [pull_request]

jobs:
  Archive:
    runs-on: macos-10.15
    timeout-minutes: 5
    steps:
      - name: "Checkout Project"
        uses: actions/checkout@v2

      - name: "Select Xcode 12.0.1"
        uses: devbotsxyz/xcode-select@master
        with:
          version: 12.0

      - name: "Import Certificate: Development"
        uses: devbotsxyz/xcode-import-certificate@master
        with:
          certificate-data: ${{ secrets.DEVELOPMENT_CERTIFICATE_DATA }}
          certificate-passphrase: ${{ secrets.DEVELOPMENT_CERTIFICATE_PASSPHRASE }}
          keychain-name: devbotsxyz-example-macos-rings
          keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}

      - name: "Archive"
        uses: devbotsxyz/xcode-archive@master
