name: Release

on:
  push:
    tags: [ v* ]

jobs:
  release:
    runs-on: macos-10.15
    timeout-minutes: 10
    steps:
      - name: "Checkout Project"
        uses: actions/checkout@v2

      #
      # Setup
      #

      - name: "Select Xcode 12.0.1"
        uses: devbotsxyz/xcode-select@master
        with:
          version: "12.0.0"

      - name: "Import Certificate: Development"
        uses: devbotsxyz/xcode-import-certificate@master
        with:
          certificate-data: ${{ secrets.DEVELOPMENT_CERTIFICATE_DATA }}
          certificate-passphrase: ${{ secrets.DEVELOPMENT_CERTIFICATE_PASSPHRASE }}
          keychain-name: devbotsxyz-example-macos-rings
          keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}

      - name: "Import Certificate: Distribution"
        uses: devbotsxyz/xcode-import-certificate@master
        with:
          certificate-data: ${{ secrets.DISTRIBUTION_CERTIFICATE_DATA }}
          certificate-passphrase: ${{ secrets.DISTRIBUTION_CERTIFICATE_PASSPHRASE }}
          keychain-name: devbotsxyz-example-macos-rings
          keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}

      #
      # First we do a developer build that we archive into an
      # .xcarchive.
      #

      - name: "Archive"
        uses: devbotsxyz/xcode-archive@master

      #
      # Next ask Xcode to export the product from the archived build
      # we just created. This will also re-sign the application with
      # the "Developer ID" certificate.
      #

      - name: "Export & Sign Release Build"
        uses: devbotsxyz/xcode-export-archive@master

      #
      # Now send the product to Apple's notarization service.
      #

      - name: "Notarize Release Build"
        uses: devbotsxyz/xcode-notarize@master
        with:
          product-path: "Export/HelloMac.app"
          username: ${{ secrets.NOTARIZATION_USERNAME }}
          password: ${{ secrets.NOTARIZATION_PASSWORD }}
